---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: javawebapp
  name: java-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: javawebapp
    spec:
      containers:
      - image: ravikumara0004/app5:0.0.3
        name: javawebapp
        ports:
        - name: javawebapp
          containerPort: 8080  
