name: Deploy test evnironment
on:
  workflow_call:
    inputs:
      project:
        required: true
        type: string
      application:
        required: true
        type: string
      github_event_pr_body:
        required: true
        type: string
       
    secrets:
      token:
        required: true

jobs:
  Updaete_PR_Body:
     runs-on: ubuntu-latest
     if: github.event_name == 'pull_request' && github.event.action != 'labeled' && github.event.action != 'closed'
     defaults:
      run:
        #shell: bash
        working-directory: ./protectbranch
     steps:
     - name: Checkout target repository
       uses: actions/checkout@v2
       with:
        repository: 'ravikumara004/protectbranch'
        token: ${{ secrets.token }}
        path: 'protectbranch'  # Optional: directory to checkout the repository
        ref: 'feature'  # Specify the branch name here

     - name: read all the file and update it on PR Descriptions
       run: |
         #!/bin/bash
         echo "${{ inputs.github_event_pr_body }}" > user_comments.yaml
         echo user_comments.yaml
         
         IFS=',' read -ra files <<< "${{ inputs.application }}"
         for app in "${files[@]}"; do

           find .template/ -type f -name "$app-value.yaml" | while IFS= read -r file; do
           echo "Processing $file"
           filename=$(basename "$file")
           value=${filename%-value.yaml}
           echo "<details>" >> out.yaml
           echo "  <summary>$value</summary>" >> out.yaml
           echo "" >> out.yaml
           echo "\`\`\`yaml" >> out.yaml
           echo "#####-$value-start-#####" >> out.yaml
           echo $value
           echo "value=$value" >> "{{ GIHUB_OUTPUT }}"
           cat "$file" >> out.yaml
           echo "#####-$value-end-#####" >> out.yaml
           echo "\`\`\`" >> out.yaml
           echo "</details>" >> out.yaml
           done

         done
